apiVersion: v1
kind: Pod
metadata: 
  name: newbusybox 
  labels: 
    env: dev 
    type: linux

spec:
  containers:
    - name: newbusybox 
      image: nginx 
      envFrom:
        - secretRef:
            name: mysecret
