apiVersion: v1 
kind: Pod 
metadata:
  name: nginx 
  labels:
    app: ngnix
    type: frontend 
spec:
  containers:
    - name: nginx 
      image: nginx 
  nodeSelector:
    size: large # Make sure the node is labelled accrodingly  
    