apiVersion: v1 
kind: Pod 
metadata:
  name: nginx 
  labels:
    app: ngnix
    type: frontend 
spec:
  - name: nginx 
    image: nginx 

tolerations:
  - key: "app"
    operator: "Equal" 
    value: "nginx"
    effect: "NoSchedule"
    