apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels: 
    app: myrsapp

spec:
  template:
    metadata: 
      name: my-pod
      labels: 
        app: myapp
        type: fn
    spec:
      containers:
      - name : nginx
        image: nginx
  replicas: 2
  selector:
    matchLabels:
      type: fn