apiVersion: v1 
kind: Service
metadata: 
  name: myservice
  namespace: dev 
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector: 
        app: devnginx
        type: frontend